### ISSUE TITLE
Hey, could you send me the full source with .sln?

### ISSUE THREAD

**Issue by Lohast** [planecobra/RustAkScriptNoRecoil#1]
My discord: x9987#6666

**Comment by l0w4nyu** [comment]
Open PolarityRecode.vcxproj big brain

**Comment by planecobra** [comment]
Its not that hard to just ctrl c and ctrl v

**Comment by Lohast** [comment]
well, i got no knowledge in c++ and this source would be helpful

**Comment by planecobra** [comment]
its fairly simple if you dont know how to paste it then learn c++
